name: chassis_forge
description: Chassis Forge is a foundation for building modern CLI apps and tools to help with project automation and other various tasks.
version: 1.2.0
homepage: https://github.com/axrs/dart_chassis_forge
repository: https://github.com/axrs/dart_chassis_forge.git
issue_tracker: https://github.com/axrs/dart_chassis_forge/issues
documentation: https://axrs.github.io/dart_chassis_forge/doc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  rucksack: '>=0.0.1 <1.0.0'
  glob: ^2.0.2
  logging: ^1.0.2
  path: ^1.8.0
  process_run: ^0.12.3+1
  reflectable: ^3.0.4
  smart_arg_fork: '>=2.4.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1

#dependency_overrides:
#  smart_arg_fork:
#    path: ../smart_arg/
